### ISSUE TITLE
Cannot run on normal browsers

### ISSUE THREAD

**Issue by lyuzhenhong** [robsci/GWplotter#1]
When I try to open the `index.html`, a message appears saying that it only works with modern browsers that support JavaScript or HTML5. However, I have checked my browser (Chrome, Safari, and Edge) and they all support these technologies.

<img width="1009" alt="截屏2023-03-29 21 50 30" src="https://user-images.githubusercontent.com/67578008/228559592-44849935-478e-48f9-9ef0-56c822607b74.png">

**Comment by cplb** [comment]
Hello @lyuzhenhong, what browser are you seeing this with? It's working fine under Chrome and Firefox for me. It could just be slow loading for you?

**Comment by lyuzhenhong** [comment]
Hello! I find everything displays normally in the web development tool. Thanks!
